[supervisord]
nodaemon=true
user=root

[program:nocodb-backend]
command=/usr/src/appEntry/start.sh
autostart=true
autorestart=true
stderr_logfile=/var/log/nocodb.err.log
stdout_logfile=/var/log/nocodb.out.log

[program:nginx]
command=nginx -g 'daemon off;'
autostart=true
autorestart=true
stderr_logfile=/var/log/nginx.err.log
stdout_logfile=/var/log/nginx.out.log
